spring:
  main.allow-bean-definition-overriding: true
  servlet.multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data.mongodb:
    authentication-database: admin
    host: mongo
    database: exchange_db
    port: 27017
  security:
    user:
      name: user
      password: bcdcTestApp
      roles: USER, ADMIN
server.port: 8090